### ISSUE TITLE
Parse arguments from the CLI

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/gcs-resumable-upload#1]
Right now, auth has to be from defaultApplication logic.

**Comment by JustinBeckwith** [comment]
👋 @stephenplusplus I'm not 100% sure what you're looking for here :) What all do you think we should accept as CLI arguments?

**Comment by stephenplusplus** [comment]
Currently, the command line only accepts a bucket and file name. So, as many options as possible should be supported!

**Comment by stephenplusplus** [comment]
(The options: https://github.com/googleapis/gcs-resumable-upload#config)

**Comment by stephenplusplus** [comment]
This was a cool feature I thought I would do when it was in stephenplusplus-land, but it's probably not in that high of demand. If anyone is out there, let us know if you want this :)
