### ISSUE TITLE
Progress event

### ISSUE THREAD

**Issue by flavioribeiro** [googleapis/gcs-resumable-upload#130]
Is it possible to hook up a `progress` event somewhere on the [OnChunk](https://github.com/googleapis/gcs-resumable-upload/blob/master/src/index.ts#L315) method so we can have something similar to what [Evaporate](https://github.com/TTLabs/EvaporateJS) does for AWS?

**Comment by JustinBeckwith** [comment]
👋 how does this look? 
https://github.com/googleapis/gcs-resumable-upload/pull/135/files

**Comment by flavioribeiro** [comment]
@JustinBeckwith the PR looks good to me, thanks for taking the time to implement it.
