### ISSUE TITLE
v0.14.0 is not on npm (faulty publish?)

### ISSUE THREAD

**Issue by mickdekkers** [googleapis/gcs-resumable-upload#169]
Hi! According to the git history and changelog in the repo, the latest version of `0.14.0` was released earlier today.

There is a link in the changelog to [the version history page on npm](https://www.npmjs.com/package/gcs-resumable-upload?activeTab=versions), but that page does not have an entry for `0.14.0`. When I `npm install` the package, it installs version `0.13.0`. I've tried manually specifying `gcs-resumable-upload@0.14.0`, but npm is unable to find that version. The [npm API](https://registry.npmjs.com/gcs-resumable-upload) also does not have an entry for `0.14.0`.

Is it possible something went wrong during the publish?

**Comment by mickdekkers** [comment]
It seems Renovate also noticed: https://github.com/googleapis/gcs-resumable-upload/pull/168

**Comment by stephenplusplus** [comment]
We have a CI bot that handles releasing to npm for us, but it only runs from 9-5 PST (currently 6:07am). So, unfortunately our release is effectively stalled for another few hours :\

**Comment by stephenplusplus** [comment]
It's out!
