### ISSUE TITLE
Chunks get lost when resuming upload with different data.

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/gcs-resumable-upload#175]
Pretty unfamiliar with this module, second pair of eyes would be good here!

It looks like we compare chunks to see if the user decided to resume the upload with different data
https://github.com/googleapis/gcs-resumable-upload/blob/master/src/index.ts#L347

If that happens, we put the chunk back in the `bufferStream`, buuut, once we restart we just toss that stream away
https://github.com/googleapis/gcs-resumable-upload/blob/master/src/index.ts#L294

I believe this would result in lost chunks, maybe?

**Comment by stephenplusplus** [comment]
I think the fix is just

const bufferStream = this.bufferStream || new PassThrough();

**Comment by callmehiphop** [comment]
Yeah, that or just creating it once in the constructor!
