### ISSUE TITLE
Cannot abort requests in Node < 8

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/gcs-resumable-upload#191]
While investigating https://github.com/googleapis/nodejs-storage/pull/619, Node 6, 8, and 10 have different reactions to the same Storage system test:

Node 10: Good code, guys!
Node 8: Upload Client Broken Connection
Node 6: Cancellation of streamed requests with AbortSignal is not supported in node < 8

That last error is thrown by fetch: https://github.com/bitinn/node-fetch/blob/e996bdab73baf996cf2dbf25643c8fe2698c3249/src/request.js#L205

I'm not sure of a way around this, exactly. We're cancelling an active HTTP request in the event of an error. Fetch is the boss on how requests made with it can be cancelled, but they're shutting out Node 6, evidently. :\

**Comment by JustinBeckwith** [comment]
Ohhhhh rats.  My opinion: 
- For this module, let's ride it out until node6 deprecation (< 1 month)
- For `nodejs-storage`, let's rollback the change upgrading to `gcs-resumable-upload` 1.0
- For Node.js 8....  gotta figure that one out 🤷‍♂️

**Comment by stephenplusplus** [comment]
Updates:

- Node 6: *unsupported in this module*
- Node 8: Tests pass!
- Node 10: Tests pass!

So, something seemed to have address the issues with Node@8 somewhere along the way.

Time to go back to Storage and make sure everything is okay over there (https://github.com/googleapis/nodejs-storage/pull/619). I don't believe there's anything left to fix here, considering the passing tests I'm seeing now. I'll close, but if anyone recalls still seeing these errors, please re-open.
