### ISSUE TITLE
Add support for non authenticated users using signed URL

### ISSUE THREAD

**Issue by yonirab** [googleapis/gcs-resumable-upload#201]
I want to be able to do resumable uploads to Google Cloud Storage in a node.js client application using this package, in conjunction with signed urls (since the client app is invoked by unauthenticated users).

My server generates a signed url and then sends a POST to the signed url with header `{ 'x-goog-resumable': 'start' }` and an empty body, and receives a response with a `location` header that looks something like the following:

    https://storage.googleapis.com/<bucket_name/<file_path>?GoogleAccessId=<service_account>&Expires=<expiry_time>&Signature=<signature>&upload_id=<upload_id>

If I return the above `location` header to my client, I would like for the client to be able to perform a resumable upload using this package, without further authentication.

I was not able to figure out how to do so using this package. If it is possible, it would be great if an example could be added in the samples.

Thanks!

**Comment by bcoe** [comment]
@jkwlui curious if this is something that can be facilitated with the signed URLs work you've done, or if you could point @yonirab in the right direction.

**Comment by z639** [comment]
@yonirab This is basically what I'm looking for too. If I understand the way this package works, you first have to upload the file to your nodejs server and from there upload to GCS, which is effectively uploading the file twice or at the very least proxying the file ?

If I can just create the initial POST request with a signed URL, either with the server or the client - although I'm getting an error of "Refused to set unsafe header "Content-Length"" in the client when trying to set the length to 0. 
Required here: https://cloud.google.com/storage/docs/xml-api/resumable-upload 

I should then be able to allow the client to perform all subsequent PUT request directly and without proxying/piping.

I think this package attempts the same https://github.com/QubitProducts/gcs-browser-upload but is very incomplete and doesn't cover the initial POST request.

If you have had or do have any joy with this then please let me know. 

Thanks.

**Comment by yonirab** [comment]
I ended up implementing the functionality myself. As usual, the google documentation on this is severely lacking and confusing, but once I figured out how it's supposed to work it was pretty straightforward.
The way it works is:
1. Client sends a request to my Server to generate a signed URL for a file it wants to upload to Google Cloud Storage.
2. Server calls [getSignedUrl](https://cloud.google.com/nodejs/docs/reference/storage/2.5.x/File#getSignedUrl) with {action: 'resumable'} in options.
3. Server sends an empty POST (with { 'x-goog-resumable': 'start' } in headers) to the signed URL to initiate a resumable upload
4. Server returns to client the URL returned in the "location" header in the response to the POST in step 3.
5. Client uploads the file directly to GCS with a PUT to the URL returned in step 4.
6. If the upload is interrupted, it can be resumed with subsequent PUTs to the same URL, this time using  Content-Range and Content-Length headers as described [here](https://cloud.google.com/storage/docs/xml-api/resumable-upload). This is the most complicated part of the whole procedure, so follow the documentation carefully.

**Comment by bcoe** [comment]
@jkwlui @JustinBeckwith sounds like this would be a great thing to add a sample for in storage potentially?

**Comment by josiahbryan** [comment]
@yonirab in your comment from last year - any chance you can share your code for step 5 and 6 ...?

**Comment by yonirab** [comment]
@josiahbryan My code looks something like this:

```
const request = require('request'),
          rp = require('request-promise-native'),
          fs = require('fs'),


// `file` is the file to upload, `url` is the resumable url
async resumeFile(file,url) {
 
     // rangeEnd is the index of the last byte in the file, i.e. number of bytes in file
      const rangeEnd = (await fs.promises.stat(file)).size;

      let rangeOptions = {
            method: 'PUT',
            url,
            headers: {
              'Content-Range': `bytes */${rangeEnd}`
            },
            simple : false,  // Expect a 308 statusCode. indicating Resume Incomplete
            resolveWithFullResponse: true,     
      };
     
      let response = await rp(rangeOptions);

      switch (response.statusCode) {
        case 200:
        case 201:
          // A 200 or 201 response indicates that the upload was completed, and no further action is necessary
          console.log('Upload complete');
          break;
        case 308:
          // Per https://cloud.google.com/storage/docs/xml-api/resumable-upload, a 308 response
          // might not contain the range header
          if (response.headers.range) {
          
            // response.headers.range should look something like this: "bytes=0-1572863",
            // so split on '-' to retrieve the number of bytes already received by Cloud Storage,
            // and add 1 to get the index of the byte from which to start the resume
            let resumeOffset = Number(response.headers.range.split('-')[1]) + 1;

            let options = {
              method: 'PUT',
              url, 
              headers: {
                'Content-Range': `bytes ${resumeOffset}-${rangeEnd-1}/${rangeEnd}`,
                'Content-Length': `${rangeEnd-resumeOffset}`,
              }     
            };

           let readStream = fs.createReadStream(file,{start:resumeOffset});
           readStream.pipe(request(options));

            break;
            
          }
        default:
          // If we get here, either we got a response other than 20x or 308, or we got a 308 without a range header.
          // In either case, we do nothing here.
          // This means that the file will still be marked as resumable and not uploaded, so we can retry later.
          break;  
      } 
}

```

**Comment by shaffeeullah** [comment]
Steps 5 and 6 above can be bypassed by using the storage `file.save` API. An example:
```
    const bucket = storage.bucket("mybucket");
    const file = bucket.file("myfile");
    const options = {
        version: 'v4',
        action: 'resumable',
        expires: Date.now() + 30 * 60 * 1000,
      };
    
    // Option 1: Create signed URL, make a post request with
    // 'x-goog-resumable' header to get the location
    // file.save with location does not require auth
    const [signedUrl] = await file.getSignedUrl(options);
    const resumableSession = await fetch(signedUrl, {
        method: 'POST',
        headers: {
            'x-goog-resumable': 'start'
        }
    });
    const location = resumableSession.headers.location;


    // Option 2: file.createResumableUpload() to get location
    // file.save with location does not require auth
    const [location] = await file.createResumableUpload();

    await file.save('content of file', {
        uri: location,
        resumable: true,
        validation: false
    });
```

**Comment by shaffeeullah** [comment]
A sample for doing this is now merged into the nodejs-storage repo, so closing this out.
