### ISSUE TITLE
tests are failing on the main branch

### ISSUE THREAD

**Issue by bcoe** [googleapis/gcs-resumable-upload#292]
https://github.com/googleapis/gcs-resumable-upload/pull/291
https://github.com/googleapis/gcs-resumable-upload/pull/290

**Comment by stephenplusplus** [comment]
@bcoe is this still going on? The linked PRs have closed now, so something must have worked itself out along the way. #296 is an open PR that has all green.

**Comment by bcoe** [comment]
@stephenplusplus sounds like we worked things out :+1:
