### ISSUE TITLE
Resumable upload with chunks

### ISSUE THREAD

**Issue by ghisSparkmate** [googleapis/gcs-resumable-upload#310]
Hi,

I'm trying to use this package on my API that receives chunks of file and then send them on GCS to reconstitute the whole file, however I'm getting stuck.

The first chunk get uploaded correctly, GCS return a response **308** as it's supposed to do (the file is smaller than the contentLength specified) which make gcs-resumable-upload throw an error. Is it normal ? I think it shouldn't throw as it's a normal behaviour for an incomplete but resumable upload.

I change to not reject my promise on error (to avoid this thing with code 308) but then the upload gets stuck on the second chunk. I get the logs of progress until a certain point where it get stucks and nothing happens. The request is retried until the point where GCS return a request timeout. I tried on several networks but it's always the same.

Below is the code I use for upload. Any clue would be greatly appreciated :)

```
const upConfig = {
    bucket: config.bucketName,
    authClient,
    file: filename,
    offset,  //Offset in bytes 
    metadata: { contentLength }, // ContentLength of the whole file, not the chunk
    public: true,
  };

return new Promise((resolve, reject) => {
    readableStream
      .pipe(upload(upConfig))
      .on('progress', progress => {
        console.log('Progress', progress);
      })
      .on('response', res => {
        console.log('GCS Response', res);
      })
      .on('finish', () => {
        console.log('Done');
        resolve();
      })
      .on('error', function(err) {
        console.error('Upload chunk error', err);
        resolve(); // don't want to reject on status code 308
      });
  });
```

**Comment by ghisSparkmate** [comment]
Hello @shaffeeullah,

It's been a while, I don't remember every details, but in the end we stopped using this SDK and switch to another solution. So on my side I'm clear with that, but the problem itself hasn't been addressed

**Comment by shaffeeullah** [comment]
I will close this for now. If anyone is seeing this issue, please re-open
