### ISSUE TITLE
Option to not rely on the local file system?

### ISSUE THREAD

**Issue by sripberger** [googleapis/gcs-resumable-upload#347]
**Is your feature request related to a problem? Please describe.**

I'm confused as to the reasoning behind the use of [configstore](https://github.com/yeoman/configstore) here. To me, it does not seem like the correct tool for the job. You're not persisting configuration. You're storing temporary data about an upload in progress.

I guess this might not be a big deal by itself, but the thing is `configstore` relies on the local file system, and does not seem to have support for using a different storage mechanism. This is a problem, because production node apps typically have more than one instance behind a load balancer-- each running it it's own container with its own local file system. This will of course cause an upload to start over completely, if a different instance serves the resumed upload than the one that was used to start it in the first place. It seems it will also cause the data in the original configstore for the upload to become orphaned, never being cleared out as the original instance is never informed that the upload has completed.

 **Describe the solution you'd like**
It would be nice to be able to store this information in something more friendly to typical production node architectures. Something like Redis, or even just temporary files in GCS itself.  With the number of people downloading this, I have a hard time believing that there isn't *some* kind of solution for this problem, so perhaps I'm just missing something.

 **Describe alternatives you've considered**

Again, unless I'm missing something, it doesn't seem like any alternatives are supported. There isn't really another library like this one, short of rolling my own against the base cloud storage node api.

**Comment by stephenplusplus** [comment]
You're right about all of it. Any interest in contributing to this library? I like all of the solutions proposed-- maybe an adapter that defaults to configstore, but can easily be swapped for a user-defined override. Something like...

```js
const uploadStream = createResumableUpload({
  bucket: '...',
  file: '...',
  model: {
    get: () => {
      return myDb.get()
    },
    set: state => {
      return myDb.set(state)
    },
    delete: () => {
      return myDb.delete()
    }
  }
})
```

Better naming conventions or ideas welcome! Thanks for taking the time to write up the issue and help us improve 👍

**Comment by sripberger** [comment]
Thanks for the prompt response.

I'd be happy to contribute this change, though at the moment I can't prioritize it. I'm in the midst of creating a new API service for my company, so I have more immediate problems.

I'll plan on coming back to do it when we get closer to putting this new service in production, though. :+1:

**Comment by B-0-B-B-Y** [comment]
Any updates on the status of this? I too am in a situation where I really need the option of storing the config somewhere not on the local file system. I am using multiple services in AppEngine, and those environments are all read-only file systems. This library has everything I need functionality wise bar the ability to read/write a config file not on the file system. It seems at the minute my two options are handle all the resumable upload logic myself and do multiple PUT requests, incrementing the content range each time, which isn't the cleanest or use `createWriteStream()` with the `resumable: false` option, which just creates more problems with large file uploads and nodejs timeouts on express routes etc. Seeing as how Google pushes you to use storage buckets for all static files your server app may need, I think it would make sense that there is some form of integration with storage buckets to read/write these config files to, and delete them as part of cleanup on having a successful file upload come back with a 200. I can try and help with getting this sorted if there is some work already done and needs carrying on?

**Comment by stephenplusplus** [comment]
@B-0-B-B-Y Thanks for offering to help. Seems like nobody has taken this one on yet. I'm happy to help with any questions along the way if you decide to give it a shot.

**Comment by B-0-B-B-Y** [comment]
Hi @stephenplusplus , okay no problems, I've forked the repo and will make a start. I am thinking since I will be doing this work, do you think we should provide universal set, get and delete methods for people, or create a more specialised solution for GCP storage buckets specifically. If we were to go with a more universal approach then obviously we remove the limitation of local file system and you can pretty much use any kind of storage you can think of at that point, but it would mean people specifically wanting to use GCP storage buckets would have to provide their own methods for reading and writing etc. as opposed to just the config necessary to init the cloud storage SDK on this package's side. Thoughts about this?

**Comment by BrennaEpp** [comment]
The use of configstore to save a file with cached url is unexpected and it means that tweaking apiEndpoints with same filename has no effect. See https://github.com/googleapis/nodejs-storage/issues/1611

**Comment by shaffeeullah** [comment]
Closed by https://github.com/googleapis/nodejs-storage/pull/1871
