### ISSUE TITLE
License discrepancy in source files vs LICENSE file

### ISSUE THREAD

**Issue by nathanmosher** [googleapis/gcs-resumable-upload#399]
It looks like the LICENSE file for this library is MIT, but the source files contain Apache licenses in JS comments. Is this discrepancy intentional?

If not, which one is the appropriate license for the library?

**Comment by frankyn** [comment]
Hi @JustinBeckwith, we saw that you were last to interact with the LICENSE file in (https://github.com/googleapis/gcs-resumable-upload/pull/73). Is there more background as to why the MIT License was used instead of Apache 2?

**Comment by danielduhh** [comment]
Thanks for calling this out @nathanmosher. The Apache headers were applied in error. This repo is under the MIT license. This will be fixed by #400
