### ISSUE TITLE
More information on error when HTTP response is not 20x

### ISSUE THREAD

**Issue by brandizzi** [googleapis/gcs-resumable-upload#448]
Hello all!

From time to time, we have some issues while trying to use gcs-resumable-upload indirectly. [It fails only with the message "Upload failed"](https://github.com/googleapis/gcs-resumable-upload/blob/master/src/index.ts#L477-L480):
```
      if (resp.status < 200 || resp.status > 299) {
        this.destroy(new Error('Upload failed'));
        return;
      }
```
We believe more information could be on the failure exception, like HTTP status and the error message. What do you think?

**Comment by ddelgrosso1** [comment]
Hi @brandizzi,

Thank you for bringing this up. Could you provide a bit more information, I assume you are using this indirectly through the storage library, is that correct? If so, what version are you using? Thanks!

**Comment by ddelgrosso1** [comment]
@brandizzi this is a changed we are interested in making. Unfortunately, because it would be a breaking change to the library it is going to be something that will need to be handled in the next major version update. I will update this issue once more details / implementation is available.

**Comment by ddelgrosso1** [comment]
@mglodack let me take a closer look at the code. This may very well be a great suggestion that does allow us to avoid a major version bump. I will circle back in a day or two.
